/** =============================================================================
 ** Copyright (c) 2003-2005 WaveTop Information Corp. All rights reserved.
 **
 ** The backup system
 **
 ** =============================================================================
 */

/* This file has been generated by TINDERBOX. */

#ifndef __WAVETOP_BACKUP_VERSION_H_
#define __WAVETOP_BACKUP_VERSION_H_ 1

#define WAVETOP_COMPANY_NAME            "WaveTop Information Corp."
#define WAVETOP_BACKUP_PRODUCT_NAME     "¿À«ÊDAYS‘÷±∏»Ìº˛"
#define WAVETOP_BACKUP_COPYRIGHT        "Copyright (c) 2003-2012 WaveTop"
#define WAVETOP_BACKUP_PRODUCT_VERSION  "4.1.0"

#define WAVETOP_BACKUP_FILE_DESCRIPTION "WaveTop Backup system"
#define WAVETOP_BACKUP_FILE_VERSION     "4.1.0.0.20120731"

#define WAVETOP_BACKUP_FILE_VERSION_NUM 0

#define WAVETOP_BACKUP_VERSION_MAJOR    4
#define WAVETOP_BACKUP_VERSION_MINER    1
#define WAVETOP_BACKUP_VERSION_REVISION 0


#endif 

