/** =============================================================================
 ** Copyright (c) 2003 WaveTop Information Corp. All rights reserved.
 **
 ** The backup system
 **
 ** =============================================================================
 */

/* The compile options. This file has been generated by compile script. */

#ifndef __WAVETOP_BACKUP_COMPILE_H_
#define __WAVETOP_BACKUP_COMPILE_H_ 1 

#ifdef WIN32
#include <time.h>
#include <winsock2.h>
#include <MSTcpIP.h> //LW add
#else
#include <sys/socket.h>
#include <netinet/tcp.h>
#include <errno.h>
#include <sys/timeb.h>
#include <sys/time.h>
#include <unistd.h>
#include <ctype.h>
#ifdef SOLARIS
#include <sys/filio.h>
#else   /* #ifdef SOLARIS */
#include <sys/ioctl.h>
#endif  /* #ifdef SOLARIS */
#endif  /* #ifdef WIN32 */

/* 终端备份标志 */
// #define WAVETOP_BACKUP_BACKUP				 10

#ifdef WAVETOP_BACKUP_BACKUP
/* 共享版本编译开关 */
#define WAVETOP_BACKUP_SHARE_VERSION        1
#else
#define WAVETOP_BACKUP_SHARE_VERSION        0
#endif

/* 简化版本用户最多个数 (50)*/
#define WAVETOP_BACKUP_USER_COUNT_LIMIT     50

/* 简化版本用户最大限额 (20G)*/
#define WAVETOP_BACKUP_USER_QUOTA_LIMIT     20480

/* 定义执行版本个数后强制做全量 (终端备份) */
#define WAVETOP_BACKUP_BACKUP_VERSION_FULL   (1<<7)

/* 0为正式版，1为试用版 */
#define WAVETOP_BACKUP_DEMO_VERSION         0

/* 实时备份标志,注释掉为ACDP */
#define WAVETOP_BACKUP_PROD_BACKUP6         1   

/* 区分公务网数据备份或服务器备份 */
/*#define WAVETOP_BACKUP_CIVIL_SERVICE_NETWORK 0*/
				
/* User Synch Synchronization switch */
#define WAVETOP_BACKUP_USER_SYNCH_VERSION   0

#endif // __WAVETOP_BACKUP_COMPILE_H_ 1

